# Your registries
registries:
  dockerhub:
    address: default
  k8s:
    address: registry.k8s.io
    folder: k8s.io
  dev:
    address: harbor-dev.mydomain.local/docker
  prd:
    address: harbor-prd.mydomain.local/docker

# Lists of container images
# Define jobs to copy lists of container images from one registry to another
jobs:
  k8s-to-dev:
    source: k8s
    target: dev
    imagelists:
    - kubernetes_k8s
  dockerhub-to-dev:
    source: dockerhub
    target: dev
    imagelists:
    - gitlab
    - kubernetes
    - postgres
    - ubuntu
    - vault
  dev-to-prd:
    source: dev
    target: prd
    imagelists:
    - kubernetes_k8s
    - kubernetes
    - postgres

# Define your imagelists down here
imagelists:
  gitlab:
    - name: gitlab/gitlab-ee:15.7.0-ee.0
    - name: gitlab/gitlab-runner-helper:ubuntu-x86_64-v14.10.2
  kubernetes:
    - name: calico/apiserver:v3.24.5
    - name: calico/cni:v3.24.5
    - name: calico/kube-controllers:v3.24.5
    - name: calico/node:v3.24.5
    - name: calico/pod2daemon-flexvol:v3.24.5
    - name: calico/typha:v3.24.5
    - name: grafana/grafana:9.2.3
    - name: k8s.gcr.io/pause:3.6
    - name: library/traefik:2.9.4
  kubernetes_k8s:
    - name: coredns:v1.9.3
    - name: etcd:3.5.4-0
    - name: kube-apiserver:v1.25.0
    - name: kube-controller-manager:v1.25.0
    - name: kube-proxy:v1.25.0
    - name: kube-scheduler:v1.25.0
    - name: pause:3.8
    - name: coredns/coredns:v1.9.3
  postgres:
    - name: library/postgres:15.1-alpine
  ubuntu:
    - name: ubuntu:20.04
      lts: true
    - name: ubuntu:22.04
      lts: true
    - name: ubuntu:24.04
      lts: true
  vault:
    - name: library/vault:1.11.4
